# Generated by Django 2.2.13 on 2020-08-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('student_count', models.IntegerField()),
                ('staff_count', models.IntegerField()),
                ('students_joined', models.IntegerField()),
                ('students_completed', models.IntegerField()),
                ('students_dropped', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_phone', models.CharField(max_length=150, unique=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254)),
                ('manager_id', models.IntegerField()),
                ('doj', models.DateField()),
                ('employee_status', models.CharField(max_length=50)),
                ('leaves_applied', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Support_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('batch_id', models.IntegerField()),
                ('enrolled_course', models.CharField(max_length=50)),
                ('enrolled_date', models.DateField()),
                ('attendance', models.FloatField()),
                ('course_status', models.BooleanField()),
                ('placement_status', models.BooleanField()),
            ],
        ),
    ]
