# Generated by Django 2.2.13 on 2020-08-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0002_audit_hr_support_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_team',
            name='course_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='support_team',
            name='placement_status',
            field=models.CharField(max_length=50),
        ),
    ]
