# Generated by Django 2.2.13 on 2020-08-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0003_auto_20200816_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_team',
            name='enrolled_date',
            field=models.CharField(max_length=50),
        ),
    ]
