# Generated by Django 2.2.13 on 2020-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuva', '0005_auto_20200816_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='leaves_applied',
            field=models.IntegerField(),
        ),
    ]
